export const GET__POST = "GET__POST";
export const GET_SINGLE_USER = "GET_SINGLE_USER";
export const GET_SINGLE_USER_POSTS = "GET_SINGLE_USER_POSTS";
export const DELETE_SINGLE_USER_POST = "DELETE_SINGLE_USER_POST";
